/**
 * iCal sync utilities — server-side only (Node.js).
 * Parses an iCal feed URL and returns half-open date intervals [start, end).
 *
 * RRULE note: recurring events are skipped in this MVP. Recurrence instances
 * generated by the organizer as individual VEVENT components are included
 * (most external-calendar exports work this way).
 */

import { format, parseISO, addDays } from 'date-fns'

type BusyInterval = {
  start: string // yyyy-MM-dd
  end: string   // yyyy-MM-dd (exclusive / half-open)
  summary: string
}

/** Fetch and parse an iCal URL; returns busy intervals as half-open [start, end) date pairs. */
export async function fetchICalBusyIntervals(url: string): Promise<BusyInterval[]> {
  // Dynamic import so this module is only evaluated server-side.
  const ical = await import('node-ical')

  let data: Record<string, unknown>
  try {
    // node-ical.async.fromURL handles http/https and returns parsed events map.
    data = await ical.async.fromURL(url)
  } catch (err) {
    throw new Error(`Failed to fetch iCal feed: ${err instanceof Error ? err.message : String(err)}`)
  }

  const intervals: BusyInterval[] = []

  for (const component of Object.values(data)) {
    if (typeof component !== 'object' || component === null) continue
    const c = component as Record<string, unknown>

    if (c.type !== 'VEVENT') continue

    // Skip recurring event definitions (RRULEs); individual instances are fine.
    if (c.rrule) continue

    const summary = typeof c.summary === 'string' ? c.summary : 'Busy'

    // node-ical gives start/end as Date (with .dateOnly flag for all-day events).
    const rawStart = c.start as Date & { dateOnly?: boolean }
    const rawEnd   = c.end   as Date & { dateOnly?: boolean }

    if (!(rawStart instanceof Date) || isNaN(rawStart.getTime())) continue

    const startStr = toDateString(rawStart)

    // All-day events: end is the exclusive date as-is in iCal (DTEND is day after last day).
    // Timed events: end could be on a different date — use the calendar date of end.
    let endStr: string
    if (!rawEnd || isNaN((rawEnd as Date).getTime())) {
      // No end date: treat as single-day (block one night [start, start+1))
      endStr = toDateString(addDays(parseISO(startStr), 1))
    } else {
      endStr = toDateString(rawEnd)
      // Safety: ensure end > start
      if (endStr <= startStr) {
        endStr = toDateString(addDays(parseISO(startStr), 1))
      }
    }

    intervals.push({ start: startStr, end: endStr, summary })
  }

  return intervals
}

function toDateString(d: Date): string {
  // Use local date parts — iCal all-day events carry the "wall clock" date
  // without timezone, so we avoid UTC offset shifting.
  const y  = d.getFullYear()
  const mo = String(d.getMonth() + 1).padStart(2, '0')
  const dy = String(d.getDate()).padStart(2, '0')
  return `${y}-${mo}-${dy}`
}
